version: "3"

services:
    app:
        build: .
        stop_signal: SIGINT
        container_name: assistant_bot
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./:/app
        depends_on:
            - db
        networks:
            - assist-network

    db:
        image: postgres:14-alpine
        container_name: assist_postgres_db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - assist-network

networks:
  assist-network:

